# Synthetic demo data - not real production data.
"""
Auditable Artifact Bundle Generator for IncidentPilot.
"""

import json
from typing import Dict, Any


def generate_artifact_bundle(incident_id: str, finish_data: dict, diff_info: dict, test_data: dict, timeline: list, evidence_graph: dict, verifier_data: dict) -> Dict[str, str]:
    """
    Generates downloadable artifact files for the incident post-mortem:
    1. incident_INC-4821.md
    2. evidence_INC-4821.json
    3. patch_INC-4821.diff
    4. verification_INC-4821.json
    5. timeline_INC-4821.json
    """

    # 1. Markdown Report
    evidence_items = "\n".join([f"- `{e}`" for e in finish_data.get("evidence_ids", [])])
    root_cause = finish_data.get("root_cause", "")
    why = finish_data.get("why", "")
    resolution = finish_data.get("resolution", "")
    prevention = finish_data.get("prevention", "")
    lines_added = diff_info.get("lines_added", 0)
    lines_removed = diff_info.get("lines_removed", 0)
    passed_tests = test_data.get("passed", 12)
    total_tests = test_data.get("total", 12)

    md_report = f"""# AUDITABLE INCIDENT RESOLUTION REPORT — {incident_id}

**Target Service:** `checkout` | **Severity:** `HIGH` | **Deployment:** `v2.4.1`  
**Verification Status:** `VERIFIED SAFE FOR HUMAN REVIEW` | **Confidence:** `HIGH (97%)`

---

## 1. Executive Summary
An elevated HTTP 500 error rate (spiking from 0.8% to 31.4%) was detected on the `/v1/checkout` endpoint following deployment `v2.4.1`. Requests containing expired coupons were returning HTTP 500 Internal Error instead of the expected HTTP 400 Bad Request.

## 2. Evidence Correlation & Root Cause
- **Root Cause:** {root_cause}
- **Introduction Mechanic:** {why}

### Evidence Chain Cited:
{evidence_items}

## 3. Multi-Hypothesis Evaluation
- **H1 (Coupon Validation Exception Handler Bug):** CONFIRMED (Confidence: 68% -> 82% -> 97%)
- **H2 (DB Connection Pool Exhaustion):** REJECTED (Confidence: 21% -> 2%)
- **H3 (Payment Gateway Timeout):** REJECTED (Confidence: 11% -> 1%)

## 4. Failure Reproduction & Counterfactual Proof
- **Before Patch:** Payload `{{"coupon": "EXPIRED_SAVE20"}}` -> `HTTP 500 Internal Error`
- **After Patch:** Payload `{{"coupon": "EXPIRED_SAVE20"}}` -> `HTTP 400 Bad Request`

## 5. Verified Patch & Risk Assessment
- **Resolution:** {resolution}
- **Patch Risk Rating:** `LOW` (Blast radius restricted to coupon exception branch)
- **Patch Metrics:** `+{lines_added}` lines added, `-{lines_removed}` lines removed.

## 6. Double-Check Verification Gate
- **Pytest Results:** `{passed_tests}/{total_tests}` Passed (0 Failures)
- **Adversarial Verifier:** `CLAIM_CONFIRMED` (0 Regressions, error status preserved)
- **Human Approval Required:** `YES`

## 7. Preventative Recommendations
{prevention}

---
*Generated by IncidentPilot Autonomous SRE Ops Agent — Synthetic Demo Environment*
"""

    # 2. Evidence JSON
    evidence_json = json.dumps(evidence_graph, indent=2)

    # 3. Patch Diff
    patch_diff = diff_info.get("diff_text", "# No diff available")

    # 4. Verification JSON
    verification_json = json.dumps({
        "incident_id": incident_id,
        "verification_status": "VERIFIED SAFE FOR HUMAN REVIEW",
        "tests": test_data,
        "verifier": verifier_data
    }, indent=2)

    # 5. Timeline JSON
    timeline_json = json.dumps(timeline, indent=2)

    return {
        f"incident_{incident_id}.md": md_report,
        f"evidence_{incident_id}.json": evidence_json,
        f"patch_{incident_id}.diff": patch_diff,
        f"verification_{incident_id}.json": verification_json,
        f"timeline_{incident_id}.json": timeline_json
    }
